services:
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
  postgres:
   image: postgres
   environment:
    - POSTGRES_PASSWORD=admin
  redis:
    image: "redis:latest"
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
        - POSTGRES_PASSWORD=admin
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - postgres
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports: 
      - "3050:80"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app